version: "3.8"

services:
  db:
    container_name: database
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: books
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minionetwork
    volumes:
      - "minio_data:/data"
    environment:
      MINIO_ROOT_USER: "your_username"
      MINIO_ROOT_PASSWORD: "your_pasword"
      MINIO_DEFAULT_BUCKETS: "storage"

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
